# Generated by Django 4.0.2 on 2022-03-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
