version: '3.9'

services:

  innotter_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: "innotter_db"
      POSTGRES_PASSWORD: 1234567!
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5672:5672

  django:
    container_name: innotter_django
    build:
      context: ./
      dockerfile: Dockerfile
    command:  bash -c "python src/manage.py migrate --noinput &&
              python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - innotter_db
      - fastapi

  celery:
    restart: always
    build:
      context: ./
    command: bash -c  "cd src && celery -A proj worker -l info -P gevent"
    volumes:
      - .:/src
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: "innotter_db"
      POSTGRES_PASSWORD: 1234567!
    depends_on:
      - innotter_db
      - django

  fastapi:
    container_name: innotter_fastapi
    build:
      context: ./
    command:  bash -c "cd microservice && uvicorn main:app --host 0.0.0.0 --port 8001"
    volumes:
      - .:/microservice
    ports:
      - 8001:8001

  consumer:
    container_name: innotter_consumer
    build:
      context: ./
    command:  bash -c "cd microservice && python consumer.py"
    volumes:
      - .:/microservice 
volumes:
  postgres_data: