# Generated by Django 4.0.2 on 2022-03-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='follow_requests',
        ),
        migrations.RemoveField(
            model_name='page',
            name='followers',
        ),
    ]
