# Generated by Django 4.0.2 on 2022-03-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='reply_to',
        ),
    ]
