# Generated by Django 4.0.2 on 2022-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_follow_requests_remove_page_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to=''),
        ),
    ]
