# Generated by Django 4.0.2 on 2022-03-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('pages', '0004_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tags.tag'),
        ),
    ]
