# Generated by Django 4.0.2 on 2022-03-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='count_follow_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='count_followers',
            field=models.IntegerField(default=0),
        ),
    ]
