# Generated by Django 4.0.2 on 2022-03-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
